config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
    root to: "places#index"

    resources :places, only: [:index, :show, :new, :create] do
      resources :entries, only: [:new, :create]
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :entries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def new
    @place = Place.find(params[:place_id])
    @entry = Entry.new(place: @place)
  end

  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      redirect_to place_path(@entry.place_id)
    else
      @place = Place.find(entry_params[:place_id])
      render :new
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :description, :occurred_on, :place_id)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all.order(:name)
  end

  def show
    @place = Place.find(params[:id])
    @entries = @place.entries.order(occurred_on: :desc)
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to places_path
    else
      render :new
    end
  end

  private

  def place_params
    params.require(:place).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/new.html.erb
<h1>New Entry for <%= @place.name %></h1>

<%= form_with(model: @entry, url: place_entries_path(@place), local: true) do |f| %>
  <%= f.hidden_field :place_id, value: @place.id %>

  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :occurred_on, "Date" %><br>
    <%= f.date_field :occurred_on %>
  </div>

  <div>
    <%= f.submit "Create Entry" %>
  </div>
<% end %>

<p><%= link_to "Back to ", place_path(@place) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StarterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/index.html.erb
<h1>Places</h1>

<ul>
  <% @places.each do |place| %>
    <li><%= link_to place.name, place_path(place) %></li>
  <% end %>
</ul>

<%= link_to "Add New Place", new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= form_with(model: @place, local: true) do |f| %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.submit "Create Place" %>
  </div>
<% end %>

<p><%= link_to "Back to Places", places_path %></p>

app/views/places/show.html.erb
<h1><%= @place.name %></h1>

<p><%= link_to "Back to Places", places_path %></p>

<h2>Entries</h2>

<% if @entries.any? %>
  <p>
    <% @entries.each do |entry| %>
        <h3><%= entry.title %></h3> <br><%= entry.occurred_on %>
        <p><%= entry.description %></p>
    <% end %>
  </p>
<% else %>
  <p>No entries yet.</p>
<% end %>

<%= link_to "New Post", new_place_entry_path(@place) %>